PATRIOT_SAMPLE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('sample.urls')),
]
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

sample/urls.py
from django.urls import path

app_name = 'sample'

from .views import *

urlpatterns = [
    path('', LandingPage.as_view(),name='products'),
    path('product/add/', add_product, name='add_product'),
    path('product/edit/<uuid:prod_id>/', UpdateProduct.as_view(), name='edit_product'),
    path('product/delete/<uuid:prod_id>/', delete_product, name='delete_product'),
    
    path('categories/', categories,name='categories'),
    path('categories/<uuid:category_id>/', edit_categories,name='edit_categories'),

    
    
]

sample/models.py
from .utils import ACTIVE
from django.db import models
import uuid

# Create your models here.
from django.contrib.auth.models import User

class Category(models.Model):
    id = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        primary_key=True
    )
    name = models.CharField(max_length=256)
    description     =   models.TextField(blank=True,null=True)
    created_at    =   models.DateTimeField(auto_now_add=True)
    updated_at   =   models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='category_user')
    status   =   models.CharField(max_length=255,default=ACTIVE)    
        
    def __str__(self):                           
        return self.name



class Product(models.Model):
    id = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        primary_key=True
    )
    category = models.ForeignKey(Category,on_delete=models.SET_NULL,null=True, blank=True,related_name='product_category')
    name = models.CharField(max_length=256)
    image = models.ImageField(null=True, blank=True,upload_to='products/')
    description     =   models.TextField(blank=True,null=True)
    created_at    =   models.DateTimeField(auto_now_add=True)
    updated_at   =   models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True,related_name='product_user')
    status   =   models.CharField(max_length=255,default=ACTIVE)    
        
    def __str__(self):                           
        return self.name

sample/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string

# Create your views here.
from django.views.generic.list import ListView
from .utils import ACTIVE, DELETE
from .models import *
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from rest_framework.views import APIView
import json

class LandingPage(ListView):
    template_name = "product/product.html"
    context_object_name = 'products'
    model = Product
    
    def get_queryset(self) :
        return self.model.objects.filter(status=ACTIVE)
    
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['categories'] = Category.objects.filter(status=ACTIVE)
        return context
    

  
def add_product(request, **kwargs):
    try:
        category_id = request.POST.get('add_category', None)
        category= Category.objects.filter(id=category_id).first()
        if not category:
            return JsonResponse({'status':False,'msg':"Category not found"})
        name = request.POST.get('name', None)
        description = request.POST.get('description', None)
        image = request.FILES.get('image')
        Product.objects.create(
            name = name, description = description, category=category,image=image
        )
        products = Product.objects.filter(status=ACTIVE)
        template=render_to_string('product/product_list.html',{'products': products})
        return JsonResponse({'status':True,"msg":"Product add Succesfully",'template':template})
    except Exception as e:
        return JsonResponse({'status':False, "msg" : str(e)}) 


class UpdateProduct(APIView):

    def put(self, request, prod_id):
        try:
            product = Product.objects.filter(id=prod_id).first()
            if not product:
                return Response({'msg': "Product not found"}, status=status.HTTP_400_BAD_REQUEST)
            category_id = request.POST.get('edit_category', None)
            category= Category.objects.filter(id=category_id).first()
            if not category:
                return Response({'msg': "Category not found"}, status=status.HTTP_400_BAD_REQUEST)
            name = request.POST.get('edit_name', None)
            description = request.POST.get('edit_description', None)
            image = request.FILES.get('edit_image')
            product.name = name
            product.category = category
            product.description = description
            product.image = image
            product.save()
            return Response({'msg': 'Edit Success fully'}, status=status.HTTP_200_OK)
        except Exception as e:
            return Response({'msg': str(e)}, status=status.HTTP_200_OK)
        
    

def delete_product(request, prod_id):
    try:
        product = Product.objects.filter(id=prod_id).first()
        if not product:
            return Response({'msg': "Product not found"}, status=status.HTTP_400_BAD_REQUEST)
        product.status = DELETE
        product.save()
        return JsonResponse({'status':True,"msg":"Product Delete Succesfully",})
    except Exception as e:
        return JsonResponse({'status':False, "msg" : str(e)}) 
    

def categories(request):
    if request.method == 'POST':
        categories_data = json.loads(request.body.decode('utf-8'))
        categories_datas  = categories_data.get('datas', None)
        for category in categories_datas:
            Category.objects.create(**category)
        products = Category.objects.filter(status=ACTIVE)
        template=render_to_string('category/category_list.html',{'categories': products})
        return JsonResponse({"msg" :"Category created successfully","template":template},status=status.HTTP_200_OK) 
    categories = Category.objects.all()
    context = {"categories":categories}
    return render(request, 'category/category.html',context)


def edit_categories(request,category_id):
    if request.method == 'POST':
        category = Category.objects.filter(id=category_id).first()
        if not category:
            return JsonResponse({"msg" :"Category Not Found"}, status=400) 
        name = request.POST.get('name')
        description = request.POST.get('description')
        category.name = name
        category.description = description
        category.save()
        return JsonResponse({"msg" :"Category Update successfully"},status=200) 
    return JsonResponse({'message': 'Invalid request method'}, status=400)

templates/base-layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="" type="image/png" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
    <title>{% block title_content %}{% endblock title_content %}</title>

    <link rel="stylesheet" href="{% static 'css/layout.css' %}" />
    {% block static_content %}{% endblock static_content %}
  </head>
  <body id="body-pd">
    <header class="header" id="header">
      <div class="header_toggle">
        <i class="bx bx-menu" id="header-toggle"></i>
      </div>
      <div class="header_img">
        <img src="https://i.imgur.com/hczKIze.jpg" alt="" />
      </div>
    </header>
    <div class="l-navbar" id="nav-bar">
      <nav class="nav">
        <div>
          <a href="#" class="nav_logo">
            <i class="bx bx-layer nav_logo-icon"></i>
            <span class="nav_logo-name">BBBootstrap</span>
          </a>
          <div class="nav_list">
            <a href="{% url 'sample:products' %}" class="nav_link active">
              <i class="bx bx-grid-alt nav_icon"></i>
              <span class="nav_name">Product</span>
            </a>
            <a href="{% url 'sample:categories' %}" class="nav_link">
              <i class="bx bx-user nav_icon"></i>
              <span class="nav_name">Category</span>
            </a>
            <a href="#" class="nav_link">
              <i class="bx bx-message-square-detail nav_icon"></i>
              <span class="nav_name">Messages</span>
            </a>
            <a href="#" class="nav_link">
              <i class="bx bx-bookmark nav_icon"></i>
              <span class="nav_name">Bookmark</span>
            </a>
            <a href="#" class="nav_link">
              <i class="bx bx-folder nav_icon"></i>
              <span class="nav_name">Files</span>
            </a>
            <a href="#" class="nav_link">
              <i class="bx bx-bar-chart-alt-2 nav_icon"></i>
              <span class="nav_name">Stats</span>
            </a>
          </div>
        </div>
        <a href="#" class="nav_link">
          <i class="bx bx-log-out nav_icon"></i>
          <span class="nav_name">SignOut</span>
        </a>
      </nav>
    </div>
    <!--Container Main start-->
    <div class="height-100 bg-light">
      <div class="container mt-5 pt-1">{% block content %}{% endblock content %}</div>
    </div>
    <!--Container Main end-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="{% static 'js/layout.js' %}"></script>
    {% block js_content %}{% endblock js_content %}
  </body>
</html>

templates/category/add.html
<!-- Button trigger modal -->

  
  <!-- Modal -->
  <div class="modal fade" id="add-category" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Add Category</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="p-2">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody id="dynamicadd">
                  <tr id="row-0">
                    <td >
                        <input type="text" class="form-control" name="name">
                        <p class="text-danger" id="name-error-0"></p>
                    </td>
                    <td>
                      <input type="text" class="form-control" name="description">
                      <p class="text-danger" id="description-error-0"></p>
                    </td>
                    <td>
                      <a type="button" id="add" class="form-control bg-success btn"><span class="text-light font-weight-bold">&PlusMinus;</span></a>
                    </td>
                  </tr>
                </tbody>
            </table>
            <div class="btn-primary btn float-end" id="save">Save</div>
        </div>
      </div>
    </div>
  </div>

templates/category/category.html
{% extends "base-layout.html" %}
{% load static %}

{% block title_content %}Category List{% endblock title_content %}

{% block static_content %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css"/>
<link rel="stylesheet"href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css"/>
{% endblock static_content %} 


{% block content %}
<div class="mt-3">
    <button type="button" class="btn btn-primary mb-3" data-toggle="modal" data-target="#add-category" style="float: right;">ADD NEW</button>
    {% include 'category/add.html' %}
    <div id="categories-responce-data">
        {% include "category/category_list.html" %}
    </div>
</div>

{% endblock content %} 


{% block js_content %}

<script>

    $(document).ready(()=>{
        var i = 0;

        function check_validation(i){
            let name = $(`#row-${i} [name="name"]`).val();
            let description = $(`#row-${i} [name="description"]`).val();
            
            if (description.trim() === "" && name.trim() === "") {
                $(`#name-error-${i}`).text("Name is required").show();
                $(`#description-error-${i}`).text("Description is required").show();
            } else {
                $(`#name-error-${i}`).hide();
                $(`#description-error-${i}`).hide();
            }

            if (name.trim() === "") {
                $(`#name-error-${i}`).text("Name is required").show();
            } else {
                $(`#name-error-${i}`).hide();
            }
            
            if (description.trim() === "") {
                $(`#description-error-${i}`).text("Description is required").show();
            } else {
                $(`#description-error-${i}`).hide();
            }
            
            if (name.trim() === "" || description.trim() === "") {
                return false;
            }
        }

        function lastrownumber() {
            let numRows = $('#dynamicadd tr').length;
            let lastRowId;
            $('#dynamicadd tr').each(function() {
                lastRowId = $(this).attr('id');
            });
            const parts = lastRowId.split('-');
            return parts[1];
        }
        
        $('#add').click(()=>{
            lastid = lastrownumber()
            if (check_validation(lastid) == false){
                return false;
            }
            i++;
            $('#dynamicadd').append(`
            <tr id="row-${i}">
                <td ><input type="text" class="form-control" name="name" >
                    <p class="text-danger" id="name-error-${i}"></p></td>
                <td><input type="text" class="form-control" name="description" >
                    <p class="text-danger" id="description-error-${i}"></p></td>
                <td><button  id="${i}" class="form-control bg-danger btn btn_remove"><span class="text-light font-weight-bold">&PlusMinus;</span></button></td>
            </tr>`
            )
        });

        $(document).on('click','.btn_remove',function(){
            var row_id = $(this).attr('id');
            $('#row-'+row_id).remove();
        })


        $('#save').click(() => {
            lastid = lastrownumber()
            if (check_validation(lastid) == false){
                return false;
            }
            var postData = [];

            $('#dynamicadd tr').each(function () {
                var rowId = $(this).attr('id');
                var name = $(`#${rowId} [name="name"]`).val();
                var description = $(`#${rowId} [name="description"]`).val();

                if (name.trim() !== "" && description.trim() !== "") {
                    postData.push({
                        "name": name,
                        "description": description,
                    });
                }
            });

            // console.log(JSON.stringify(postData));
            datas = {"datas":postData}
            const headers = {
                'X-CSRFToken':'{{ csrf_token }}',
              };
            axios.post('{% url "sample:categories" %}', datas, {headers}
            ).then((res) => {
                if (res.status == 200){
                    $('#categories-responce-data').html(res.data.template);
                    Swal.fire({
                        position: 'top-end',
                        icon: 'success',
                        title: res.data.msg,
                        showConfirmButton: false,
                        timer: 2000
                    })
                }
                else{
                    Swal.fire({
                        position: 'top-end',
                        icon: 'error',
                        title: res.data.msg,
                        showConfirmButton: false,
                        timer: 2000
                    })
                }
                $("#add-category" + " .close").click();
            })
            .catch((error) => {
                Swal.fire({
                    position: 'top-end',
                    icon: 'error',
                    title: error,
                    showConfirmButton: false,
                    timer: 2000
                })
                $("#add-category" + " .close").click();
            });
        });
    })

    function edit_category(pk){
        const form = document.getElementById('edit-category-' + pk)
        const formdata = new FormData(form);
        const headers = {
            'X-CSRFToken':'{{ csrf_token }}'
        };
        url = form.action
        axios.post(url, formdata, {headers}).then((res)=>{
            if (res.status == 200){
                    Swal.fire({
                        position: 'top-end',
                        icon: 'success',
                        title: res.data.msg,
                        showConfirmButton: false,
                        timer: 2000
                    })
                }
            else {
                Swal.fire({
                    position: 'top-end',
                    icon: 'error',
                    title: res.data.msg,
                    showConfirmButton: false,
                    timer: 2000
                })
            }
            $("#edit-category-"+ pk).find('form').trigger('reset');
            $(`#add-category-${pk}` + " .close").click();
            window.location.reload()
        })
    }
</script>
{% endblock js_content %}

templates/category/category_list.html
<table id="example" class="table table-striped" style="width: 100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Created_at</th>
      <th>created_by</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for category  in  categories %}
    <tr>
      <td>{{category.name}}</td>
      <td>{{category.description}}</td>
      <td>{{category.created_at}}</td>
      <td>{{category.created_by}}</td>
      <td>
        <a class="ml-1" href="javascript:void(0)" data-toggle="modal" data-target="#add-category-{{category.id}}" title="Edit"
        data-toggle="tooltip">
        <i class="fa fa-edit color-muted"></i></a>
      
      <a href="#" onclick="" class="ml-1" data-toggle="tooltip" data-placement="top"
        title="Delete"><i class="fa fa-trash-o fa-lg"></i></a>
      </td>
    </tr>
    {% include 'category/edit.html' %}
    {% endfor %}
  </tbody>
</table>

templates/category/edit.html
<!-- Button trigger modal -->

  
  <!-- Modal -->
  <div class="modal fade" id="add-category-{{category.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Edit Category</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="p-2">
            <form action="{% url 'sample:edit_categories' category_id=category.id %}" method="post" id="edit-category-{{category.id}}" >
                {% csrf_token %}
                <input type="text" class="form-control m-1" name="name" value="{{category.name}}">
                <input type="text" class="form-control m-1" name="description" value="{{category.description}}">
                <button type="button" class="btn btn-primary float-end" onclick="edit_category('{{category.id}}')">Edit Save</button>
            </form>
        </div>
      </div>
    </div>
  </div>

templates/product/add.html
<!-- Button trigger modal -->

  
  <!-- Modal -->
  <div class="modal fade" id="add-product" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Add Product</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
    <form action="javascript:void(0)" id="product-add-form" enctype="multipart/form-data" >
        <div class="modal-body">
                {% csrf_token %}
                <div class="form-group row">
                    <select name="add_category"  class="form-control" > 
                        <option value="" disabled selected hidden>Select Category</option> 
                        {% for category in categories %}
                        <option value="{{category.id}}">{{category.name}}</option>
                        {% endfor %}
                    </select>
                  </div>

                <div class="form-group row">
                  <label for="name-product" class="col-sm-2 col-form-label">Name</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" name="name" value="example">
                  </div>
                </div>

                <div class="form-group row">
                  <label for="image-product" class="col-sm-2 col-form-label">image</label>
                  <div class="col-sm-10">
                        <input type="file" class="form-control" accept="image/*" placeholder="Enter Product Image"  name="image">
                </div>
                </div>

                  <div class="form-group row">
                    <label for="description" class="col-sm-2 col-form-label">Description</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control"  name="description" placeholder="Description">
                    </div>
                </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
    </form>
      </div>
    </div>
  </div>

templates/product/edit.html
<!-- Button trigger modal -->

  
  <!-- Modal -->
  <div class="modal fade" id="add-product-{{product.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Edit Product</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
    <form action="javascript:void(0)" id="product-edit-form-{{product.id}}" onsubmit="edit_product('{{product.id}}')" enctype="multipart/form-data" >
      {% csrf_token %}
        <div class="modal-body">
                <div class="form-group row">
                    <select name="edit_category"  class="form-control" > 
                        <option value="" disabled selected hidden>Select Category</option> 
                        {% for category in categories %}
                        <option value="{{category.id}}" 
                        {% if category.id == product.category.id %}
                        selected 
                        {% endif %}>{{category.name}}</option>
                        {% endfor %}
                    </select>
                  </div>

                <div class="form-group row">
                  <label for="name-product" class="col-sm-2 col-form-label">Name</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" name="edit_name" value="{{product.name}}">
                  </div>
                </div>

              <div>
                {% if product.image  %}
                  <img src="{{product.image.url}}" alt="" height="80px" width="80px">
                {% else %}
                  <img src="" alt="No Image" height="80px" width="80px">
                {% endif %}
              </div>

                <div class="form-group row">
                  <label for="image-product" class="col-sm-2 col-form-label">image</label>
                  <div class="col-sm-10">
                        <input type="file" class="form-control" accept="image/*" placeholder="Enter Product Image"  name="edit_image">
                </div>
                </div>

                  <div class="form-group row">
                    <label for="description" class="col-sm-2 col-form-label">Description</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control"  value="{{product.description}}" name="edit_description" placeholder="Description">
                    </div>
                </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
    </form>
      </div>
    </div>
  </div>

templates/product/product.html
{% extends "base-layout.html" %}
{% load static %}

{% block title_content %}Product_list{% endblock title_content %}

{% block static_content %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/dataTables.bootstrap5.min.css"/>
<link rel="stylesheet"href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css"/>
{% endblock static_content %} 


{% block content %}
  <div class="mt-3">
    <button type="button" class="btn btn-primary mb-3" data-toggle="modal" data-target="#add-product" style="float: right;">ADD NEW</button>
    {% include 'product/add.html' %}
    <div id="responce-data">
      {% include 'product/product_list.html' %}
    </div>  
  </div>
{% endblock content %} 


{% block js_content %}
  
<script>

  const form = document.getElementById('product-add-form')
  $('#product-add-form').on('submit', async function (event) {
        event.preventDefault();
        const formdata = new FormData(form);
        await axios.post('{% url "sample:add_product" %}', formdata).then((res) => {
            if (res.data.status) {
                $('#responce-data').html(res.data.template);
                Swal.fire({
                    position: 'top-end',
                    icon: 'success',
                    title: 'Add Success fully',
                    showConfirmButton: false,
                    timer: 2000
                })
                // model data reset
                $("#add-product").find('form').trigger('reset');
                // modal close button click 
                $("#add-product" + " .close").click();
            }else{
                Swal.fire({
                    position: 'top-end',
                    icon: 'error',
                    title: res.data.msg,
                    showConfirmButton: false,
                    timer: 1500
                })
                $("#add-product").find('form').trigger('reset');
                // modal close button click 
                $("#add-product" + " .close").click();
            }
        })
  });

  function edit_product(pk) {
      const form = document.getElementById('product-edit-form-' + pk)
      const formdata = new FormData(form);
      const headers = {
        'X-CSRFToken':'{{ csrf_token }}'
      };
      axios.put('http://127.0.0.1:8000/product/edit/'+ pk + '/', formdata, { headers }).then((res) => {
        console.log(res.data)
        if (res.status == 200) {
            $('#responce-data').html(res.data.template);
            Swal.fire({
                position: 'top-end',
                icon: 'success',
                title: 'Edit Success fully',
                showConfirmButton: false,
                timer: 2000
            })
        }else{
            Swal.fire({
                position: 'top-end',
                icon: 'error',
                title: res.data.msg,
                showConfirmButton: false,
                timer: 1500
            })
        }
      window.location.reload()
    })
  }


  function delete_product(pk) {
    Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
    }).then((result) => {
        if (result.isConfirmed) {
          let data = new FormData();
          data.append("csrfmiddlewaretoken", '{{csrf_token}}')
          axios.post('http://127.0.0.1:8000/product/delete/'+ pk + '/', data).then((res) => {
              if (res.data.data) {
                  Swal.fire({
                      position: 'top-end',
                      icon: 'success',
                      title: 'Delete Success fully',
                      showConfirmButton: false,
                      timer: 2000
                  })
              }
              window.location.reload()
          })
        }
    })
  }
    
</script>
  
{% endblock js_content %}